[package]
name = "education"
version = "0.1.0"
edition = "2021"
authors = ["hardglitch"]

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1

[dependencies]
rand = "0.8.5"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"